trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest' # Choose a suitable agent pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Use a supported Node.js version
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)' # Root of the repository
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'  # Use your build command (e.g., build, prod, dist)
    workingDir: '$(System.DefaultWorkingDirectory)'
  displayName: 'npm build'

- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_app_name: 'augur-dashboard' # Replace with your Static Web App name
    app_location: '.'   # Root of the repository
    api_location: ''   # Leave blank for frontend-only apps
    output_location: 'dist'   # Directory where your build output resides (e.g., dist, build)
    azure_static_web_app_resource_group_name: 'ujayadhar'
    skip_app_build: true  # because we already built it above
    skip_api_build: true

  displayName: 'Deploy to Azure Static Web App'
